apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telegram-bot
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
type: Opaque
stringData:
  token: {{ .Values.telegram.token | quote }}